/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solera.pingpong.adrucociamer;
import com.solera.pingpong.fizzbuzz.FizzBuzz;
import com.solera.pingpong.romannumerals.RomanNumerals;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	System.out.println(new FizzBuzz(315).calcFizzBuzz());
    	System.out.println(new RomanNumerals(531).intToRoman());
        System.out.println(new App().getGreeting());
    }
}
